# Generated by Django 5.1.4 on 2024-12-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_photo_userconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_status',
            field=models.CharField(choices=[('new', 'New'), ('code_verified', 'Code Verified'), ('done', 'Done'), ('photo_uploaded', 'Photo Uploaded')], default='new', max_length=31),
        ),
    ]
